name: "hugegraph-client-go-ci"

on:
  push:
    branches:
      - master
      - feature-go-client
      - /^release-.*$/
      - /^feature-.*$/
    paths:
      - hugegraph-client-go/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-client-go/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml

jobs:
  client-go-ci:
    runs-on: ubuntu-20.04
    env:
      TRAVIS_DIR: hugegraph-client/assembly/travis
      COMMIT_ID: c8e0f0c3e12a47694501703e2cabfc9bd97d671c
    strategy:
      fail-fast: false
      matrix:
        JAVA_VERSION: ['8']
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-hugegraph-from-source.sh $COMMIT_ID

      - name: Init Go env
        uses: actions/setup-go@v2.1.3
        with: { go-version: '1.x' }

      - name: Go test
        run: |
          go version  
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
          cd hugegraph-client-go && make test